name: Conventional PR Title

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  check-title:
    name: Conventional PR Title
    runs-on: ubuntu-latest
    
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
